- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - ../roles/test
#    - role2

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
