- hosts: all
  become: yes
  gather_facts: yes

#  roles:
#    - role1
#    - role2

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
